# Generated by Django 5.2.10 on 2026-01-30 01:23

import uuid

import django.db.migrations.operations.special
import django.db.models.deletion
import opaque_keys.edx.django.models
import openedx_django_lib.fields
import openedx_django_lib.validators
from django.conf import settings
from django.db import migrations, models

from cms.djangoapps.contentstore.config.waffle import ENABLE_CHECKLISTS_QUALITY
from cms.djangoapps.contentstore.toggles import ENABLE_REACT_MARKDOWN_EDITOR


def create_checklists_quality_waffle_flag(apps, schema_editor):
    Flag = apps.get_model('waffle', 'Flag')
    # Replacement for flag_undefined_default=True on flag definition
    Flag.objects.get_or_create(name=ENABLE_CHECKLISTS_QUALITY.name, defaults={'everyone': True})


def create_markdown_editor_waffle_flag(apps, schema_editor):
    Flag = apps.get_model('waffle', 'Flag')
    Flag.objects.get_or_create(
        name=ENABLE_REACT_MARKDOWN_EDITOR.name, defaults={'everyone': True}
    )


class Migration(migrations.Migration):

    replaces = [('contentstore', '0001_initial'), ('contentstore', '0002_add_assets_page_flag'), ('contentstore', '0003_remove_assets_page_flag'), ('contentstore', '0004_remove_push_notification_configmodel_table'), ('contentstore', '0005_add_enable_checklists_quality_waffle_flag'), ('contentstore', '0006_courseoutlineregenerate'), ('contentstore', '0007_backfillcoursetabsconfig'), ('contentstore', '0008_cleanstalecertificateavailabilitydatesconfig'), ('contentstore', '0009_learningcontextlinksstatus_publishableentitylink'), ('contentstore', '0010_container_link_models'), ('contentstore', '0011_enable_markdown_editor_flag_by_default'), ('contentstore', '0012_componentlink_top_level_parent_and_more'), ('contentstore', '0013_componentlink_downstream_is_modified_and_more'), ('contentstore', '0014_remove_componentlink_downstream_is_modified_and_more'), ('contentstore', '0015_switch_to_openedx_content')]

    initial = True

    dependencies = [
        ('course_overviews', '0024_overview_adds_has_highlights'),
        ('oel_components', '0003_remove_componentversioncontent_learner_downloadable'),
        ('oel_publishing', '0002_alter_learningpackage_key_and_more'),
        ('oel_publishing', '0003_containers'),
        ('openedx_content', '0002_rename_tables_to_openedx_content'),
        ('waffle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('profile_whitelist', models.TextField(blank=True, help_text='A comma-separated list of names of profiles to include in video encoding downloads.')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=create_checklists_quality_waffle_flag,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='CourseOutlineRegenerate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('course_overviews.courseoverview',),
        ),
        migrations.CreateModel(
            name='BackfillCourseTabsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('start_index', models.IntegerField(default=0, help_text='Index of first course to start backfilling (in an alphabetically sorted list of courses)')),
                ('count', models.IntegerField(default=0, help_text='How many courses to backfill in this run (or zero for all courses)')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'verbose_name': 'Arguments for backfill_course_tabs',
                'verbose_name_plural': 'Arguments for backfill_course_tabs',
            },
        ),
        migrations.CreateModel(
            name='CleanStaleCertificateAvailabilityDatesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('arguments', models.TextField(blank=True, help_text="A space seperated collection of arguments to be used when running the `clean_stale_certificate_available_dates` management command.' See the management command for options.")),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'verbose_name': "Arguments for 'clean_stale_certificate_availability_dates'",
                'verbose_name_plural': "Arguments for 'clean_stale_certificate_availability_dates'",
            },
        ),
        migrations.CreateModel(
            name='LearningContextLinksStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', opaque_keys.edx.django.models.CourseKeyField(help_text='Linking status for course context key', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], help_text='Status of links in given learning context/course.', max_length=20)),
                ('created', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('updated', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
            ],
            options={
                'verbose_name': 'Learning Context Links status',
                'verbose_name_plural': 'Learning Context Links status',
            },
        ),
        migrations.CreateModel(
            name='ComponentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('upstream_usage_key', opaque_keys.edx.django.models.UsageKeyField(help_text='Upstream block usage key, this value cannot be null and useful to track upstream library blocks that do not exist yet', max_length=255)),
                ('upstream_context_key', openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, db_index=True, help_text='Upstream context key i.e., learning_package/library key', max_length=500)),
                ('downstream_usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255, unique=True)),
                ('downstream_context_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('version_synced', models.IntegerField()),
                ('version_declined', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('updated', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('upstream_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='openedx_content.component')),
            ],
            options={
                'verbose_name': 'Component Link',
                'verbose_name_plural': 'Component Links',
            },
        ),
        migrations.CreateModel(
            name='ContainerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('upstream_context_key', openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, db_index=True, help_text='Upstream context key i.e., learning_package/library key', max_length=500)),
                ('downstream_usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255, unique=True)),
                ('downstream_context_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('version_synced', models.IntegerField()),
                ('version_declined', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('updated', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('upstream_container_key', opaque_keys.edx.django.models.ContainerKeyField(help_text='Upstream block key (e.g. lct:...), this value cannot be null and is useful to track upstream library blocks that do not exist yet or were deleted.', max_length=255)),
                ('upstream_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='openedx_content.container')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Container Link',
                'verbose_name_plural': 'Container Links',
            },
        ),
        migrations.RunPython(
            code=create_markdown_editor_waffle_flag,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='componentlink',
            name='top_level_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentstore.containerlink'),
        ),
        migrations.AddField(
            model_name='containerlink',
            name='top_level_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentstore.containerlink'),
        ),
        migrations.AddField(
            model_name='componentlink',
            name='downstream_customized',
            field=models.JSONField(default=list, help_text='Names of the fields which have values set on the upstream block yet have been explicitly overridden on this downstream block'),
        ),
        migrations.AddField(
            model_name='containerlink',
            name='downstream_customized',
            field=models.JSONField(default=list, help_text='Names of the fields which have values set on the upstream block yet have been explicitly overridden on this downstream block'),
        ),
    ]
