# Generated by Django 5.2.12 on 2026-04-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_libraries', '0001_squashed_0012_switch_to_openedx_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ltigradedresource',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ltigradedresource',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='ltiprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ltiprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contentlibrary',
            name='authorized_lti_configs',
        ),
        migrations.DeleteModel(
            name='ContentLibraryBlockImportTask',
        ),
        migrations.DeleteModel(
            name='LtiGradedResource',
        ),
        migrations.DeleteModel(
            name='LtiProfile',
        ),
    ]
