# Generated by Django 5.2.11 on 2026-02-19 23:23

import django.db.models.functions.text
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Force course_id to be case-insensitively unique.

    Note: due to a bug we had for several years, it's possible that this
    migration will fail because you have some duplicate entries in the
    split_modulestore_django_splitmodulestorecourseindex database table that
    differ only in case. Note that other parts of the system (like
    CourseOverview) are case-insensitive so only allow one version of the course
    ID to be stored, but this table would allow multiple if they differ in case.
    Such courses would likely be broken/buggy because so many other parts of the
    system use a case-insensitive course_id.

    So if you encounter this issue and the migration fails due to a duplicate:
    Try to figure out which is the "correct" ID (e.g. the one used in the
    CourseOverview, CourseEnrollment, and CoursewareStudentModule tables) and
    then delete the "incorrect" ID from this table. You can easily do
    this from the Django admin at:
        (studio)/admin/split_modulestore_django/splitmodulestorecourseindex/

    Be sure to take a screenshot or record the `objectid`, `draft_version`,
    `published_version`, and `wiki_slug` fields before you do so, so that you
    can reverse the deletion if needed.

    Deleting rows from this table will NOT delete any actual course content from
    MongoDB nor cascade the deletion to any other rows in other MySQL tables; it
    just removes a duplicate record that points to [unused?] course data.
    """

    dependencies = [
        ("split_modulestore_django", "0003_alter_historicalsplitmodulestorecourseindex_options"),
    ]

    operations = [
        # Make 'course_id' case-insensitively unique (in addition to its existing case-sensitively unique index)
        migrations.AddConstraint(
            model_name="splitmodulestorecourseindex",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("course_id"),
                name="splitmodulestorecourseindex_courseid_unique_ci",
            ),
        ),
        # Mark the 'course_id' field as 'case_sensitive=True' now that LearningContextKeyField supports it upstream.
        # This part of the migration should have no effect on the database, as migration 0001 already explicitly set a
        # case-sensitive collation. We just now have a way to indicate that in the model field definition.
        migrations.AlterField(
            model_name="splitmodulestorecourseindex",
            name="course_id",
            field=opaque_keys.edx.django.models.LearningContextKeyField(
                case_sensitive=True, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalsplitmodulestorecourseindex",
            name="course_id",
            field=opaque_keys.edx.django.models.LearningContextKeyField(
                case_sensitive=True, db_index=True, max_length=255
            ),
        ),
    ]
