name: Quality checks

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - open-release/lilac.master

jobs:
  run_tests:
    name: Quality Others
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version:
          - "3.12"
        node-version: [20]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: Fetch base branch for comparison
        run: git fetch --depth=1 origin ${{ github.base_ref }}

      - name: Install Required System Packages
        run: sudo apt-get update && sudo apt-get install libxmlsec1-dev

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup npm
        run: npm i -g npm@8.5.x

      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache pip dependencies
        id: cache-dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/testing.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install Required Python Dependencies
        env:
          PIP_SRC: ${{ runner.temp }}
        run: |
          make test-requirements

      - name: Install npm
        env:
          PIP_SRC: ${{ runner.temp }}
        run: npm ci

      - name: Install python packages
        env:
          PIP_SRC: ${{ runner.temp }}
        run: |
            pip install -e .

      - name: Run Quality Tests
        env:
          PIP_SRC: ${{ runner.temp }}
          TARGET_BRANCH: ${{ github.base_ref }}
        run: |
            ruff check --output-format=github .
            make xsslint
            make pii_check
            make check_keywords

      - name: Save Job Artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build-Artifacts
          path: |
            **/reports/**/*
            test_root/log/**/*.log
            *.log
          overwrite: true
